title: Julia P. / Tech Writer
email: petrova751@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  From crafting developer docs from scratch to maintaining them for the long term, Iâ€™ve got you covered
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

#theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack
plugins:
  - jekyll-feed
    
accent_image: none

menu:
  - title:             About
    url:               /about/
  - title:             Portfolio
    url:               /samples/
  - title:             Resume
    url:               /resume/
    
author:
  social:
    email: petrova751@gmail.com
    linkedin: julia-petrova-tech-writer
    github:  Julia-Petrova



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
